# Exportar datos a sql

In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("clean_data.csv")
df.head()

,Unnamed: 0,author,description,likes,comments,shares,plays,hashtags,music,create_time,video_url
0,0,dalebrisby90,"That sounds like JB, ima go with TRUTH! #rode...",44800,125,1863,686000,"That sounds like JB, ima go with TRUTH! 🤔🤣 #ro...",original sound,2025-05-19 15:45:53.000000000,https://www.tiktok.com/@dalebrisby90/video/750...
1,1,jessicafloriolli,thanks for sticking around @Alonzofloriolli,285700,290,963,1200000,thanks for sticking around @Alonzofloriolli,ECE Marketing Airball,2025-05-22 17:02:36.000000000,https://www.tiktok.com/@jessicafloriolli/video...
2,2,ay_2fya,#publicinterview #fyp #rizz,38000,65,496,416100,#publicinterview #fyp #rizz,original sound,2025-05-22 15:05:21.000000000,https://www.tiktok.com/@ay_2fya/video/75072863...
3,3,abell1823,Boat days hit different,87200,259,23600,725800,Boat days hit different ✨,If You Were Mine,2025-05-20 22:43:34.000000000,https://www.tiktok.com/@abell1823/video/750666...
4,4,jordanmarielynnxoxo,a lululemonnnn. #prettygirl #foryoupage #trend...,77600,724,1196,362100,a lululemonnnn. #prettygirl #foryoupage #trend...,What Da Fuk,2025-05-20 20:32:12.000000000,https://www.tiktok.com/@jordanmarielynnxoxo/vi...

In [37]:
df["description"] = df["description"].fillna("Sin descripción")
df.isnull().sum()

Unnamed: 0     0
author         0
description    0
likes          0
comments       0
shares         0
plays          0
hashtags       0
music          0
create_time    0
video_url      0
dtype: int64

### Cambiar nombre de variables conforme el modelo dimencional


# Dimencion author
author  ->   author_name

# Dimencion video
video_id  -> video_id_tiktok
video_url
description
hashtags
music

# Dimencion tiempo
create_time	  -> fecha_completa

# Tabla de hechos
likes
comments
shares
plays

In [38]:
df = df.rename(columns={
    "author": "author_name",
    "create_time": "fecha_completa",
})

In [39]:
df.head()

,Unnamed: 0,author_name,description,likes,comments,shares,plays,hashtags,music,fecha_completa,video_url
0,0,dalebrisby90,"That sounds like JB, ima go with TRUTH! #rode...",44800,125,1863,686000,"That sounds like JB, ima go with TRUTH! 🤔🤣 #ro...",original sound,2025-05-19 15:45:53.000000000,https://www.tiktok.com/@dalebrisby90/video/750...
1,1,jessicafloriolli,thanks for sticking around @Alonzofloriolli,285700,290,963,1200000,thanks for sticking around @Alonzofloriolli,ECE Marketing Airball,2025-05-22 17:02:36.000000000,https://www.tiktok.com/@jessicafloriolli/video...
2,2,ay_2fya,#publicinterview #fyp #rizz,38000,65,496,416100,#publicinterview #fyp #rizz,original sound,2025-05-22 15:05:21.000000000,https://www.tiktok.com/@ay_2fya/video/75072863...
3,3,abell1823,Boat days hit different,87200,259,23600,725800,Boat days hit different ✨,If You Were Mine,2025-05-20 22:43:34.000000000,https://www.tiktok.com/@abell1823/video/750666...
4,4,jordanmarielynnxoxo,a lululemonnnn. #prettygirl #foryoupage #trend...,77600,724,1196,362100,a lululemonnnn. #prettygirl #foryoupage #trend...,What Da Fuk,2025-05-20 20:32:12.000000000,https://www.tiktok.com/@jordanmarielynnxoxo/vi...

## Crear dimenciones de mi modelo estrella

#### Dimencion author

In [40]:
Dim_Author = df[["author_name"]].reset_index(drop=True)

In [41]:
Dim_Author.head()

           author_name
0         dalebrisby90
1     jessicafloriolli
2              ay_2fya
3            abell1823
4  jordanmarielynnxoxo

#### Dimencion video

In [42]:
Dim_Video = df[[
    "video_url",
    "description",
    "hashtags",
    "music"
]].reset_index(drop=True)

In [43]:
Dim_Video = Dim_Video.applymap(lambda x: str(x).encode("utf-8", "ignore").decode("utf-8"))

C:\Users\luigu\AppData\Local\Temp\ipykernel_21112\4002153215.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  Dim_Video = Dim_Video.applymap(lambda x: str(x).encode("utf-8", "ignore").decode("utf-8"))

In [44]:
Dim_Video.head()

,video_url,description,hashtags,music
0,https://www.tiktok.com/@dalebrisby90/video/750...,"That sounds like JB, ima go with TRUTH! #rode...","That sounds like JB, ima go with TRUTH! 🤔🤣 #ro...",original sound
1,https://www.tiktok.com/@jessicafloriolli/video...,thanks for sticking around @Alonzofloriolli,thanks for sticking around @Alonzofloriolli,ECE Marketing Airball
2,https://www.tiktok.com/@ay_2fya/video/75072863...,#publicinterview #fyp #rizz,#publicinterview #fyp #rizz,original sound
3,https://www.tiktok.com/@abell1823/video/750666...,Boat days hit different,Boat days hit different ✨,If You Were Mine
4,https://www.tiktok.com/@jordanmarielynnxoxo/vi...,a lululemonnnn. #prettygirl #foryoupage #trend...,a lululemonnnn. #prettygirl #foryoupage #trend...,What Da Fuk

### Dimencion fecha

In [45]:
df["fecha_completa"] = pd.to_datetime(df["fecha_completa"])

Dim_Tiempo = df[["fecha_completa"]].copy()
Dim_Tiempo["anio"] = Dim_Tiempo["fecha_completa"].dt.year
Dim_Tiempo["trimestre"] = Dim_Tiempo["fecha_completa"].dt.quarter
Dim_Tiempo["mes"] = Dim_Tiempo["fecha_completa"].dt.month
Dim_Tiempo["nombre_mes"] = Dim_Tiempo["fecha_completa"].dt.strftime("%B")
Dim_Tiempo["fecha_completa"] = Dim_Tiempo["fecha_completa"].dt.date

Dim_Tiempo = Dim_Tiempo.reset_index(drop=True)

In [46]:
Dim_Tiempo.head()

  fecha_completa  anio  trimestre  mes nombre_mes
0     2025-05-19  2025          2    5        May
1     2025-05-22  2025          2    5        May
2     2025-05-22  2025          2    5        May
3     2025-05-20  2025          2    5        May
4     2025-05-20  2025          2    5        May

### Tabla de hechos

In [47]:
Fact_TikTok_Metrics = df[["plays","shares","comments","likes"]].reset_index(drop=True)
Fact_TikTok_Metrics["id_video"] = Fact_TikTok_Metrics.index + 1
Fact_TikTok_Metrics["id_author"] = Fact_TikTok_Metrics.index + 1
Fact_TikTok_Metrics["id_date"] = Fact_TikTok_Metrics.index + 1
Fact_TikTok_Metrics = Fact_TikTok_Metrics[["id_video","id_author","id_date","plays","shares","comments","likes"]]

In [48]:
Fact_TikTok_Metrics.head()

   id_video  id_author  id_date    plays  shares  comments   likes
0         1          1        1   686000    1863       125   44800
1         2          2        2  1200000     963       290  285700
2         3          3        3   416100     496        65   38000
3         4          4        4   725800   23600       259   87200
4         5          5        5   362100    1196       724   77600

## Exportar a SQL

In [49]:
Dim_Author.to_csv("Dim_Author.csv", index=False, encoding="utf-8")
Dim_Video.to_csv(
    "Dim_Video.csv",
    index=False,
    encoding="utf-8-sig"
)
Dim_Tiempo.to_csv("Dim_Tiempo.csv", index=False, encoding="utf-8")
Fact_TikTok_Metrics.to_csv("Fact_TikTok_Metrics.csv", index=False, encoding="utf-8")